# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4345c3d644a95b7912ab9c1bc93c25c1510d6e101739b5b8456eadd4b38c4b973f55fef6d45f95fe6e9f9fdd7f7780c9dca641a1428429b1e26262cd9c6ad666

test:
  secret_key_base: 4153870afca59a976ab780c38fb06ed46237d84ce4a0814defb4d456424f583b430ef456f5a11c2211fff5df16b0624d202e80ece523efad07eda32543a724e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
